global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@yourdomain.com"
  smtp_auth_username: ""
  smtp_auth_password: ""

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
    - match:
        severity: warning
      receiver: "warning-alerts"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://webhook:9000/hooks/backup-notification"
        send_resolved: true

  - name: "critical-alerts"
    webhook_configs:
      - url: "http://webhook:9000/hooks/critical-alert"
        send_resolved: true
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "#alerts"
        title: "Critical Alert: {{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"

  - name: "warning-alerts"
    webhook_configs:
      - url: "http://webhook:9000/hooks/backup-notification"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
