global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "wordpress-cluster"
    replica: "prometheus-1"

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

  # cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s

  # PostgreSQL Exporter
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    scrape_interval: 30s

  # Backup Monitor
  - job_name: "backup-monitor"
    static_configs:
      - targets: ["backup-monitor:9091"]
    scrape_interval: 60s

  # WordPress Application (if metrics endpoint available)
  - job_name: "wordpress"
    static_configs:
      - targets: ["wordpress:9000"]
    scrape_interval: 30s
    metrics_path: "/metrics"
    scrape_timeout: 10s
